### ISSUE TITLE
Name should be 'FontName' not 'FontNameWithWeight' or should define both.

### ISSUE THREAD

**Issue by tracker1** [eomttt/font-face-setter#1]
The browser will match by weight when specified match against family/weight... otherwise it will try to adapt the unweighted match wich can lead to skewed rendering. Define the "normal" last, and default should be a weight of 400.

You can "optionally" specify each weight, without a `font-weight` property under a separate name if so desired, but would not be the recommended use. for weighted variants.

```
@font-face {
  font-family: 'FontName';
  src: url('public/fonts/FontNameThin.woff2') format('woff2');
  font-weight: 100;
  font-display: swap;
}

@font-face {
  font-family: 'FontName';
  src: url('public/fonts/FontName.woff2') format('woff2');
  font-weight: 400;
  font-display: swap;
}
```

**Comment by eomttt** [comment]
Thanks for issue.
You say that Set `font-weight: 400` is default. right?

**Comment by tracker1** [comment]
Sorry for late reply... yes, 400 is default.
