### ISSUE TITLE
incorrect @font-face src

### ISSUE THREAD

**Issue by mindaugasvcs** [eomttt/font-face-setter#2]
Hi,
@font-face src value is incorrect if 'prefix' and / or 'output' is provided either via command-line or a config file.

**Comment by eomttt** [comment]
@mindaugasvcs hmm what meaning?
please show example

**Comment by mindaugasvcs** [comment]
INPUT:
gen-font-face --config font-face.config.json

font-face.config.json
{
  "dir": "dist/assets/fonts",
  "prefix": "../fonts",
  "weight": {
    "Thin": 100,
    "ExtraLight": 200,
    "Light": 300,
    "Regular": 400,
    "Medium": 500,
    "SemiBold": 600,
    "Bold": 700,
    "ExtraBold": 800,
    "Black": 900
  },
  "style": {
    "font-style": "normal",
    "font-display": "swap"
  }
}


OUTPUT:
fonts.css
@font-face {
 font-family: 'Gilroy';
 src: url('../fonts/Gilroy') format('woff2');
 font-weight: 700;
 font-style: normal;
 font-display: swap;
}
@font-face {
 font-family: 'Gilroy';
 src: url('../fonts/Gilroy') format('woff2');
 font-weight: 500;
 font-style: normal;
 font-display: swap;
}
@font-face {
 font-family: 'Gilroy';
 src: url('../fonts/Gilroy') format('woff2');
 font-weight: 400;
 font-style: normal;
 font-display: swap;
}
@font-face {
 font-family: 'Gilroy';
 src: url('../fonts/Gilroy') format('woff2');
 font-weight: 600;
 font-style: normal;
 font-display: swap;
}

Also, could you make this config default so that no config file is required for the most often used settings for "prefix", "weight" and "style"?

**Comment by mindaugasvcs** [comment]
INPUT:
font-face.config.json
{
  "dir": "dist/assets/fonts",
  "weight": {
    "Thin": 100,
    "ExtraLight": 200,
    "Light": 300,
    "Regular": 400,
    "Medium": 500,
    "SemiBold": 600,
    "Bold": 700,
    "ExtraBold": 800,
    "Black": 900
  },
  "style": {
    "font-style": "normal",
    "font-display": "swap"
  }
}

OUTPUT:
fonts.css
@font-face {
 font-family: 'Gilroy';
 src: url('/dist/assets/fonts/Gilroy-Bold.woff2') format('woff2');
 font-weight: 700;
 font-style: normal;
 font-display: swap;
}
@font-face {
 font-family: 'Gilroy';
 src: url('/dist/assets/fonts/Gilroy-Medium.woff2') format('woff2');
 font-weight: 500;
 font-style: normal;
 font-display: swap;
}
@font-face {
 font-family: 'Gilroy';
 src: url('/dist/assets/fonts/Gilroy-Regular.woff2') format('woff2');
 font-weight: 400;
 font-style: normal;
 font-display: swap;
}
@font-face {
 font-family: 'Gilroy';
 src: url('/dist/assets/fonts/Gilroy-SemiBold.woff2') format('woff2');
 font-weight: 600;
 font-style: normal;
 font-display: swap;
}

**Comment by eomttt** [comment]
I fix prefix bug https://github.com/eomttt/font-face-setter/commit/4a7e14f5582eb670de4caf942c55e298ffdff60f

**Comment by eomttt** [comment]
and cli prefix options has already exist
https://github.com/eomttt/font-face-setter#usage

**Comment by mindaugasvcs** [comment]
> and cli prefix options has already exist https://github.com/eomttt/font-face-setter#usage

I meant all the values from the config file I provided should be default.
